### ISSUE TITLE
GSAP bonus plugins

### ISSUE THREAD

**Issue by bracketsdigital** [ivodolenc/nuxt-gsap-module#4]
Hi. Please could you advise how we might be able to use this with our GSAP Business account to use the bonus plugins, such as MorphSVG? 
many thanks,

**Comment by ivodolenc** [comment]
Hi, good question and thanks for bringing this up. Unfortunately, with this module, you can only use free plugins (at least for now).

This is due to GSAP licensing. Here are official [instructions](https://greensock.com/docs/v3/Installation#private) on how you can use `premium` plugins.

Before I published this module to `npm`, I contacted the GSAP team because I was concerned about licenses and didn't want to violate copyright rules.

They were very kind and gave me the green light after some changes. They also suggested it would be great if the module could provide support for `premium` plugins.

I’m currently working on a few other projects so I'd be more than happy if someone wants to take a look and maybe create `PR` as new `feature` (add support for premium plugins).

Also, here are [instructions](https://greensock.com/forums/topic/21961-plugin-issue-with-gsap3-npm-and-nuxtjs/?tab=comments#comment-131935) on how you can manually integrate GSAP into Nuxt.

Hope this has been helpful and feel free to ask if you need additional help.

**Comment by violacase** [comment]
Hi, Ivo,
Please consider reading [(https://greensock.com/forums/topic/21961-plugin-issue-with-gsap3-npm-and-nuxtjs/?do=findComment&comment=135100&_rid=32402)]

**Comment by ivodolenc** [comment]
Hi, thanks for mention @violacase

**Comment by ivodolenc** [comment]
Hey @bracketsdigital @violacase, I just added support for `premium` plugins. See [docs.](https://github.com/ivodolenc/nuxt-gsap-module#club-greensock)

I tested it with `CustomEase` and it seems to work fine.

Feel free to try it and let me know if everything works as expected.

**Installation**

1. Follow the [official](https://youtu.be/30CivTsqqMY?t=87) instructions and install the `premium` plugins as usual.
2. After installation, simply activate the desired plugins and that's it, you're ready to go!

---

Available in the latest version: `1.3.0`

**Comment by ivodolenc** [comment]
Closing this as resolved.

**Comment by bracketsdigital** [comment]
Hi Ivo, trying to reach you via the email address on your site to see if you're interested in taking on some work, but can't through...

**Comment by ivodolenc** [comment]
Hey @bracketsdigital, yeah, the current address on the portfolio isn't valid, I need to update the site 🤷‍♂️ 😃  Feel free to contact me via [this](mailto:ivodolenc@gmail.com) email.
